spring:
  profiles:
    active: dev
    group:
      dev: dev-file
      prod: prod-file

---
spring:
  config:
    activate:
      on-profile: dev-file

environment: dev

---
spring:
  config:
    activate:
      on-profile: test-file

environment: test
---
spring:
  config:
    activate:
      on-profile: prod-file

environment: prod