spring:
  redis:
    host: 192.168.0.10
    port: 6379
    password: xiangxue@1qazXSW@
    timeout: 3000
    database: 0
    lettuce:
      pool:
        max-active: 3000
        max-wait: 3000
        max-idle: 10
        min-idle: 0