spring:
  application:
    name: file-encryption
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.10:3310/study?useSSL=false&serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useOldAliasMetadataBehavior=true
    username: root
    password: ENC(sXEm4xE5UAhod49Jow6SWrhaZCFTl9i2)
    hikari:
      pool-name: Hikari-Pool
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 180000
      max-lifetime: 180000
      connection-timeout: 5000
      connection-test-query: select 1
    type: com.zaxxer.hikari.HikariDataSource
#jasypt:
#  encryptor:
#    password: even