spring:
  redis:
    database: 0
    host: 211.149.205.3
    port: 33602
    password:
    timeout: 60s
    jedis:
      pool:
        max-active: 2000
        max-wait: 500
        min-idle: 200
        max-idle: 200
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123344
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 100
      max-wait: 10000
      initial-size: 5
      min-idle: 10
      filters: stat,wall,slf4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss